<?xml version="1.0" encoding="UTF-8"?>
<testsuites name="jest tests" tests="2" failures="2" errors="0" time="0.36">
  <testsuite name="tests/services/expense-service.test.js" errors="0" failures="2" skipped="0" timestamp="2025-03-25T23:22:19" time="0.094" tests="2">
    <testcase classname="Expense Service › addExpense" name="should add a new expense" time="0.011">
      <failure>error: database &quot;personal_finance_test&quot; does not exist
    at /Users/d/projects/personal-finance-tracker/node_modules/pg-pool/index.js:45:11
    at processTicksAndRejections (node:internal/process/task_queues:105:5)
    at Object.&lt;anonymous&gt; (/Users/d/projects/personal-finance-tracker/tests/services/expense-service.test.js:19:5)</failure>
    </testcase>
    <testcase classname="Expense Service › getExpenses" name="should return expenses for a user" time="0.005">
      <failure>error: database &quot;personal_finance_test&quot; does not exist
    at /Users/d/projects/personal-finance-tracker/node_modules/pg-pool/index.js:45:11
    at processTicksAndRejections (node:internal/process/task_queues:105:5)
    at Object.&lt;anonymous&gt; (/Users/d/projects/personal-finance-tracker/tests/services/expense-service.test.js:19:5)</failure>
    </testcase>
  </testsuite>
</testsuites>